"""empty message

Revision ID: 02890c76b174
Revises: 74c653238174
Create Date: 2020-12-18 13:36:44.194503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02890c76b174'
down_revision = '74c653238174'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('typeevent', sa.Column('event_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'typeevent', 'event', ['event_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'typeevent', type_='foreignkey')
    op.drop_column('typeevent', 'event_id')
    # ### end Alembic commands ###
