"""empty message

Revision ID: 063c2f05a624
Revises: 1cc66685dede
Create Date: 2020-12-26 01:50:53.241845

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '063c2f05a624'
down_revision = '1cc66685dede'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document', 'resource')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('resource', sa.BLOB(), nullable=True))
    # ### end Alembic commands ###
