"""empty message

Revision ID: 0b321b9d7f26
Revises: becf34d5bd9d
Create Date: 2021-04-03 23:32:17.969058

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0b321b9d7f26'
down_revision = 'becf34d5bd9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_admin_company')
    op.drop_table('user_edit_company')
    op.add_column('users', sa.Column('about', sa.String(length=350), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'about')
    op.create_table('user_edit_company',
    sa.Column('users_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('company_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], name='user_edit_company_ibfk_2'),
    sa.ForeignKeyConstraint(['users_id'], ['users.id'], name='user_edit_company_ibfk_1'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('user_admin_company',
    sa.Column('users_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('company_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], name='user_admin_company_ibfk_2'),
    sa.ForeignKeyConstraint(['users_id'], ['users.id'], name='user_admin_company_ibfk_1'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
