"""empty message

Revision ID: 0bf089390d9c
Revises: 5f73503192af
Create Date: 2021-03-16 11:11:50.628522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0bf089390d9c'
down_revision = '5f73503192af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('arena', sa.Column('creator_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'arena', 'users', ['creator_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'arena', type_='foreignkey')
    op.drop_column('arena', 'creator_id')
    # ### end Alembic commands ###
