"""empty message

Revision ID: 0ce9639ec429
Revises: ba9e1b428cf8
Create Date: 2020-11-25 00:33:51.741479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ce9639ec429'
down_revision = 'ba9e1b428cf8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('equipment', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'equipment', 'equipmentcategory', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'equipment', type_='foreignkey')
    op.drop_column('equipment', 'category_id')
    # ### end Alembic commands ###
