"""empty message

Revision ID: 0f54183bb66f
Revises: 0f90f2b2ca7d
Create Date: 2020-12-19 23:11:19.770379

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0f54183bb66f'
down_revision = '0f90f2b2ca7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('manager', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'manager', 'users', ['user_id'], ['id'])
    op.drop_column('manager', 'address')
    op.drop_column('manager', 'facebook')
    op.drop_column('manager', 'photo')
    op.drop_column('manager', 'birthday')
    op.drop_column('manager', 'instagram')
    op.drop_column('manager', 'phone')
    op.add_column('users', sa.Column('address', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('birthday', sa.Date(), nullable=True))
    op.add_column('users', sa.Column('facebook', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('instagram', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('phone', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('photo', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'photo')
    op.drop_column('users', 'phone')
    op.drop_column('users', 'instagram')
    op.drop_column('users', 'facebook')
    op.drop_column('users', 'birthday')
    op.drop_column('users', 'address')
    op.add_column('manager', sa.Column('phone', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('manager', sa.Column('instagram', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('manager', sa.Column('birthday', sa.DATE(), nullable=True))
    op.add_column('manager', sa.Column('photo', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('manager', sa.Column('facebook', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('manager', sa.Column('address', mysql.VARCHAR(length=255), nullable=True))
    op.drop_constraint(None, 'manager', type_='foreignkey')
    op.drop_column('manager', 'user_id')
    # ### end Alembic commands ###
