"""empty message

Revision ID: 12dc339be8ae
Revises: 20c5d8979481
Create Date: 2020-12-17 19:43:50.683711

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12dc339be8ae'
down_revision = '20c5d8979481'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('typehall', sa.Column('description', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('typehall', 'description')
    # ### end Alembic commands ###
