"""empty message

Revision ID: 1ca0069cc405
Revises: ebe2618dceb5
Create Date: 2021-03-16 19:26:35.735974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ca0069cc405'
down_revision = 'ebe2618dceb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('equipment', sa.Column('description', sa.String(length=256), nullable=True))
    op.add_column('equipment', sa.Column('number', sa.Integer(), nullable=True))
    op.add_column('equipment', sa.Column('power_w', sa.Integer(), nullable=True))
    op.add_column('equipment', sa.Column('rent', sa.Integer(), nullable=True))
    op.add_column('equipment', sa.Column('weight_kg', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('equipment', 'weight_kg')
    op.drop_column('equipment', 'rent')
    op.drop_column('equipment', 'power_w')
    op.drop_column('equipment', 'number')
    op.drop_column('equipment', 'description')
    # ### end Alembic commands ###
