"""empty message

Revision ID: 1d47cc69947f
Revises: 99d9763a60f5
Create Date: 2020-12-26 01:56:12.376368

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1d47cc69947f'
down_revision = '99d9763a60f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document', 'resource')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('resource', mysql.VARCHAR(length=2048), nullable=True))
    # ### end Alembic commands ###
