"""empty message

Revision ID: 1db925066b13
Revises: caa63a5114e4
Create Date: 2021-02-27 00:38:14.336133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1db925066b13'
down_revision = 'caa63a5114e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rentalcompany', sa.Column('city_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'rentalcompany', 'city', ['city_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rentalcompany', type_='foreignkey')
    op.drop_column('rentalcompany', 'city_id')
    # ### end Alembic commands ###
