"""empty message

Revision ID: 1e23acb32ac0
Revises: 5803523f66a8
Create Date: 2020-12-20 01:01:54.296209

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1e23acb32ac0'
down_revision = '5803523f66a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_constraint('event_ibfk_4', 'event', type_='foreignkey')
    op.create_foreign_key(None, 'event', 'users', ['user_id'], ['id'])
    op.drop_column('event', 'manager_id')
    op.drop_constraint('manager_ibfk_1', 'manager', type_='foreignkey')
    op.drop_column('manager', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('manager', sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('manager_ibfk_1', 'manager', 'users', ['user_id'], ['id'])
    op.add_column('event', sa.Column('manager_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'event', type_='foreignkey')
    op.create_foreign_key('event_ibfk_4', 'event', 'manager', ['manager_id'], ['id'])
    op.drop_column('event', 'user_id')
    # ### end Alembic commands ###
