"""empty message

Revision ID: 20c5d8979481
Revises: 7288b9b61122
Create Date: 2020-12-16 00:33:20.068632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20c5d8979481'
down_revision = '7288b9b61122'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('managerphoto', sa.Column('created_managerphoto', sa.DateTime(), nullable=True))
    op.add_column('managerphoto', sa.Column('edit_managerphoto', sa.DateTime(), nullable=True))
    op.add_column('managerphoto', sa.Column('manager_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'managerphoto', 'manager', ['manager_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'managerphoto', type_='foreignkey')
    op.drop_column('managerphoto', 'manager_id')
    op.drop_column('managerphoto', 'edit_managerphoto')
    op.drop_column('managerphoto', 'created_managerphoto')
    # ### end Alembic commands ###
