"""empty message

Revision ID: 22942a4cb10c
Revises: e12f1e6c7525
Create Date: 2021-01-08 21:10:30.764015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22942a4cb10c'
down_revision = 'e12f1e6c7525'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('email_admin', sa.String(length=128), nullable=True))
    op.add_column('artist', sa.Column('email_light', sa.String(length=128), nullable=True))
    op.add_column('artist', sa.Column('email_monitor', sa.String(length=128), nullable=True))
    op.add_column('artist', sa.Column('email_sound', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artist', 'email_sound')
    op.drop_column('artist', 'email_monitor')
    op.drop_column('artist', 'email_light')
    op.drop_column('artist', 'email_admin')
    # ### end Alembic commands ###
