"""empty message

Revision ID: 27d03c380909
Revises: 34e765ee4fa8
Create Date: 2021-03-16 19:09:37.185546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27d03c380909'
down_revision = '34e765ee4fa8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('equipmentsubcategory', sa.Column('equipmentcategory_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'equipmentsubcategory', 'equipmentcategory', ['equipmentcategory_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'equipmentsubcategory', type_='foreignkey')
    op.drop_column('equipmentsubcategory', 'equipmentcategory_id')
    # ### end Alembic commands ###
