"""empty message

Revision ID: 2b7e1f47211d
Revises: b548449abe4f
Create Date: 2021-03-03 00:22:22.690257

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2b7e1f47211d'
down_revision = 'b548449abe4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Settings')
    op.add_column('users', sa.Column('settings_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'settings', ['settings_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'settings_id')
    op.create_table('Settings',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
