"""empty message

Revision ID: 3c804bad8c21
Revises: f70ea21b4e85
Create Date: 2021-02-27 00:54:21.250973

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3c804bad8c21'
down_revision = 'f70ea21b4e85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rentalcompany', sa.Column('logo', sa.String(length=128), nullable=True))
    op.drop_column('rentalcompany', 'staff')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rentalcompany', sa.Column('staff', mysql.VARCHAR(length=255), nullable=True))
    op.drop_column('rentalcompany', 'logo')
    # ### end Alembic commands ###
