"""empty message

Revision ID: 40a57a3499f0
Revises: b207bacaaa8a
Create Date: 2020-12-15 22:32:46.138810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40a57a3499f0'
down_revision = 'b207bacaaa8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('manager', sa.Column('photo', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('manager', 'photo')
    # ### end Alembic commands ###
