"""empty message

Revision ID: 41455b980dd4
Revises: a0c2b36bf4fd
Create Date: 2021-03-03 01:18:07.022059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41455b980dd4'
down_revision = 'a0c2b36bf4fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invite', sa.Column('company_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invite', 'company_id')
    # ### end Alembic commands ###
