"""empty message

Revision ID: 449897c377bf
Revises: 0a621400cf37
Create Date: 2021-01-08 00:06:49.370693

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '449897c377bf'
down_revision = '0a621400cf37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('imgarena_ibfk_1', 'imgarena', type_='foreignkey')
    op.drop_column('imgarena', 'arena_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('imgarena', sa.Column('arena_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('imgarena_ibfk_1', 'imgarena', 'arena', ['arena_id'], ['id'])
    # ### end Alembic commands ###
