"""empty message

Revision ID: 4a974a13bafa
Revises: edced96f012b
Create Date: 2021-02-25 15:38:17.857970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a974a13bafa'
down_revision = 'edced96f012b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('rentalcompany_creator', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'rentalcompany', ['rentalcompany_creator'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'rentalcompany_creator')
    # ### end Alembic commands ###
