"""empty message

Revision ID: 570b178be2ec
Revises: 4830a4e3ddfd
Create Date: 2021-01-08 00:05:38.074347

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '570b178be2ec'
down_revision = '4830a4e3ddfd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('photoartist_ibfk_1', 'photoartist', type_='foreignkey')
    op.drop_column('photoartist', 'artist_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photoartist', sa.Column('artist_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('photoartist_ibfk_1', 'photoartist', 'artist', ['artist_id'], ['id'])
    # ### end Alembic commands ###
