"""empty message

Revision ID: 5803523f66a8
Revises: 6eb155364976
Create Date: 2020-12-20 00:38:00.614413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5803523f66a8'
down_revision = '6eb155364976'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('login', sa.String(length=250), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'login')
    # ### end Alembic commands ###
