"""empty message

Revision ID: 58444bf947e5
Revises: ff1aad233b5a
Create Date: 2020-12-20 23:30:09.777493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58444bf947e5'
down_revision = 'ff1aad233b5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_name', sa.String(length=250), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_name')
    # ### end Alembic commands ###
