"""empty message

Revision ID: 608fba84c8be
Revises: 12dc339be8ae
Create Date: 2020-12-17 19:53:09.240103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '608fba84c8be'
down_revision = '12dc339be8ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('typehall', sa.Column('arena_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'typehall', 'arena', ['arena_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'typehall', type_='foreignkey')
    op.drop_column('typehall', 'arena_id')
    # ### end Alembic commands ###
