"""empty message

Revision ID: 638e43d43ae8
Revises: 
Create Date: 2021-01-03 10:05:18.453520

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '638e43d43ae8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('arena', sa.Column('city_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'arena', 'city', ['city_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'arena', type_='foreignkey')
    op.drop_column('arena', 'city_id')
    # ### end Alembic commands ###
