"""empty message

Revision ID: 6826394eb12a
Revises: 6d9e3ad7c3cf
Create Date: 2021-01-20 02:59:08.756978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6826394eb12a'
down_revision = '6d9e3ad7c3cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('city_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'event', 'city', ['city_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'event', type_='foreignkey')
    op.drop_column('event', 'city_id')
    # ### end Alembic commands ###
