"""empty message

Revision ID: 6d9e3ad7c3cf
Revises: e5df8dec6b50
Create Date: 2021-01-10 13:53:28.502398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d9e3ad7c3cf'
down_revision = 'e5df8dec6b50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('arena', sa.Column('alias', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('arena', 'alias')
    # ### end Alembic commands ###
