"""empty message

Revision ID: 721f1965677d
Revises: 940ddc776dfe
Create Date: 2020-12-25 20:30:38.367061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '721f1965677d'
down_revision = '940ddc776dfe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('create_time', sa.DateTime(), nullable=True))
    op.add_column('document', sa.Column('edit_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document', 'edit_time')
    op.drop_column('document', 'create_time')
    # ### end Alembic commands ###
