"""empty message

Revision ID: 7288b9b61122
Revises: 40a57a3499f0
Create Date: 2020-12-16 00:08:15.712411

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7288b9b61122'
down_revision = '40a57a3499f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('manager', sa.Column('facebook', sa.String(length=255), nullable=True))
    op.add_column('manager', sa.Column('instagram', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('manager', 'instagram')
    op.drop_column('manager', 'facebook')
    # ### end Alembic commands ###
