"""empty message

Revision ID: 750cf9d1b081
Revises: a177129500d6
Create Date: 2020-12-22 19:02:49.631297

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '750cf9d1b081'
down_revision = 'a177129500d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'arena', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'arena', type_='unique')
    # ### end Alembic commands ###
