"""empty message

Revision ID: 792262ad35c5
Revises: 721f1965677d
Create Date: 2020-12-25 23:59:45.439154

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '792262ad35c5'
down_revision = '721f1965677d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('document_ibfk_1', 'document', type_='foreignkey')
    op.drop_column('document', 'users_id')
    op.add_column('users', sa.Column('document_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'document', ['document_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'document_id')
    op.add_column('document', sa.Column('users_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('document_ibfk_1', 'document', 'users', ['users_id'], ['id'])
    # ### end Alembic commands ###
