"""empty message

Revision ID: 7c22a27ec53a
Revises: 1465a1447f76
Create Date: 2020-11-25 00:24:34.958419

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7c22a27ec53a'
down_revision = '1465a1447f76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('equipment')
    op.add_column('tour', sa.Column('created_tour', sa.DateTime(), nullable=True))
    op.add_column('tour', sa.Column('edit_tour', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tour', 'edit_tour')
    op.drop_column('tour', 'created_tour')
    op.create_table('equipment',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
