"""empty message

Revision ID: 7eb118233657
Revises: 41455b980dd4
Create Date: 2021-03-12 00:49:01.400728

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7eb118233657'
down_revision = '41455b980dd4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('company_default_id', sa.Integer(), nullable=True))
    op.drop_constraint('settings_ibfk_1', 'settings', type_='foreignkey')
    op.create_foreign_key(None, 'settings', 'company', ['company_default_id'], ['id'])
    op.drop_column('settings', 'company_default_ip')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('company_default_ip', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'settings', type_='foreignkey')
    op.create_foreign_key('settings_ibfk_1', 'settings', 'company', ['company_default_ip'], ['id'])
    op.drop_column('settings', 'company_default_id')
    # ### end Alembic commands ###
