"""empty message

Revision ID: 85330d1b547a
Revises: 6826394eb12a
Create Date: 2021-02-25 15:12:10.396352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85330d1b547a'
down_revision = '6826394eb12a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rentalcompany', sa.Column('companytype_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'rentalcompany', 'companytype', ['companytype_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rentalcompany', type_='foreignkey')
    op.drop_column('rentalcompany', 'companytype_id')
    # ### end Alembic commands ###
