"""empty message

Revision ID: 87c62ed12fb3
Revises: def711c4f9b7
Create Date: 2021-01-03 10:21:23.225505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87c62ed12fb3'
down_revision = 'def711c4f9b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('last_name', table_name='artist')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('last_name', 'artist', ['last_name'], unique=True)
    # ### end Alembic commands ###
