"""empty message

Revision ID: 9351400cff88
Revises: 608fba84c8be
Create Date: 2020-12-17 19:59:47.152361

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9351400cff88'
down_revision = '608fba84c8be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('arena', sa.Column('typehall_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'arena', 'typehall', ['typehall_id'], ['id'])
    op.drop_constraint('typehall_ibfk_1', 'typehall', type_='foreignkey')
    op.drop_column('typehall', 'arena_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('typehall', sa.Column('arena_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('typehall_ibfk_1', 'typehall', 'arena', ['arena_id'], ['id'])
    op.drop_constraint(None, 'arena', type_='foreignkey')
    op.drop_column('arena', 'typehall_id')
    # ### end Alembic commands ###
