"""empty message

Revision ID: 936f4e6084f7
Revises: a598270b0ca7
Create Date: 2021-04-04 14:41:02.916169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '936f4e6084f7'
down_revision = 'a598270b0ca7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('privatemessages', sa.Column('recipient_id', sa.Integer(), nullable=True))
    op.add_column('privatemessages', sa.Column('sender_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'privatemessages', 'users', ['sender_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'privatemessages', type_='foreignkey')
    op.drop_column('privatemessages', 'sender_id')
    op.drop_column('privatemessages', 'recipient_id')
    # ### end Alembic commands ###
