"""empty message

Revision ID: 940ddc776dfe
Revises: d0ca37e95def
Create Date: 2020-12-25 20:29:31.830623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '940ddc776dfe'
down_revision = 'd0ca37e95def'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('users_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'document', 'users', ['users_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'document', type_='foreignkey')
    op.drop_column('document', 'users_id')
    # ### end Alembic commands ###
