"""empty message

Revision ID: 946c65661cfa
Revises: b38c2aa8d6da
Create Date: 2021-04-04 12:47:48.135696

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '946c65661cfa'
down_revision = 'b38c2aa8d6da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('private_messages')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('private_messages',
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('privatemessages_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['privatemessages_id'], ['privatemessages.id'], name='private_messages_ibfk_2'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='private_messages_ibfk_1'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
