"""empty message

Revision ID: 9803c82d64ac
Revises: 792262ad35c5
Create Date: 2020-12-26 01:22:41.222684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9803c82d64ac'
down_revision = '792262ad35c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document', 'resource')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('resource', sa.BLOB(), nullable=True))
    # ### end Alembic commands ###
