"""empty message

Revision ID: 990b8b6a3452
Revises: 97c3615b51b9
Create Date: 2020-12-26 02:05:12.130719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '990b8b6a3452'
down_revision = '97c3615b51b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document', 'resource')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('resource', sa.BLOB(), nullable=True))
    # ### end Alembic commands ###
