"""empty message

Revision ID: a0c2b36bf4fd
Revises: 2b7e1f47211d
Create Date: 2021-03-03 00:26:18.180641

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a0c2b36bf4fd'
down_revision = '2b7e1f47211d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('company_default_ip', sa.Integer(), nullable=True))
    op.drop_constraint('settings_ibfk_1', 'settings', type_='foreignkey')
    op.create_foreign_key(None, 'settings', 'company', ['company_default_ip'], ['id'])
    op.drop_column('settings', 'company_default')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('company_default', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'settings', type_='foreignkey')
    op.create_foreign_key('settings_ibfk_1', 'settings', 'company', ['company_default'], ['id'])
    op.drop_column('settings', 'company_default_ip')
    # ### end Alembic commands ###
