"""empty message

Revision ID: a1578001712d
Revises: 87c62ed12fb3
Create Date: 2021-01-03 18:26:54.810261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1578001712d'
down_revision = '87c62ed12fb3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('arena', sa.Column('sounds', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('arena', 'sounds')
    # ### end Alembic commands ###
