"""empty message

Revision ID: a177129500d6
Revises: a781363ebb20
Create Date: 2020-12-21 21:59:59.934936

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a177129500d6'
down_revision = 'a781363ebb20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('first_name', sa.String(length=250), nullable=True))
    op.add_column('users', sa.Column('patronymic', sa.String(length=250), nullable=True))
    op.drop_column('users', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', mysql.VARCHAR(length=250), nullable=True))
    op.drop_column('users', 'patronymic')
    op.drop_column('users', 'first_name')
    # ### end Alembic commands ###
