"""empty message

Revision ID: a2dae3ef7f72
Revises: a1578001712d
Create Date: 2021-01-03 18:27:06.598117

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a2dae3ef7f72'
down_revision = 'a1578001712d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('arena', 'sounds')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('arena', sa.Column('sounds', mysql.VARCHAR(length=255), nullable=True))
    # ### end Alembic commands ###
