"""empty message

Revision ID: a3e6d4092872
Revises: a376d94f8e81
Create Date: 2020-12-26 01:34:40.213754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3e6d4092872'
down_revision = 'a376d94f8e81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document', 'resource')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('resource', sa.BLOB(), nullable=True))
    # ### end Alembic commands ###
