"""empty message

Revision ID: a598270b0ca7
Revises: 0ef7b94b2e27
Create Date: 2021-04-04 14:40:38.028157

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a598270b0ca7'
down_revision = '0ef7b94b2e27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('privatemessages', 'recipient_id')
    op.drop_column('privatemessages', 'sender_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('privatemessages', sa.Column('sender_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('privatemessages', sa.Column('recipient_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
