"""empty message

Revision ID: a781363ebb20
Revises: a488cd56e9b7
Create Date: 2020-12-21 00:06:51.189853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a781363ebb20'
down_revision = 'a488cd56e9b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_users_login'), 'users', ['login'], unique=True)
    op.drop_index('login', table_name='users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('login', 'users', ['login'], unique=True)
    op.drop_index(op.f('ix_users_login'), table_name='users')
    # ### end Alembic commands ###
