"""empty message

Revision ID: b207bacaaa8a
Revises: 0ce9639ec429
Create Date: 2020-12-08 21:46:10.136341

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b207bacaaa8a'
down_revision = '0ce9639ec429'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('manager', sa.Column('address', sa.String(length=255), nullable=True))
    op.add_column('manager', sa.Column('birthday', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('manager', 'birthday')
    op.drop_column('manager', 'address')
    # ### end Alembic commands ###
