"""empty message

Revision ID: b38c2aa8d6da
Revises: 367277e923c5
Create Date: 2021-04-04 01:01:53.692190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b38c2aa8d6da'
down_revision = '367277e923c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('privatemessages', sa.Column('create', sa.DateTime(), nullable=True))
    op.add_column('privatemessages', sa.Column('edit', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('privatemessages', 'edit')
    op.drop_column('privatemessages', 'create')
    # ### end Alembic commands ###
