"""empty message

Revision ID: b548449abe4f
Revises: e674ed58e4da
Create Date: 2021-03-02 21:43:40.664587

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b548449abe4f'
down_revision = 'e674ed58e4da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('genereal_company', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'genereal_company')
    # ### end Alembic commands ###
