"""empty message

Revision ID: becf34d5bd9d
Revises: 84b1fc19dc86
Create Date: 2021-03-25 11:33:00.383324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'becf34d5bd9d'
down_revision = '84b1fc19dc86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role_in_company_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'rolescompany', ['role_in_company_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'role_in_company_id')
    # ### end Alembic commands ###
