"""empty message

Revision ID: c995e3096be8
Revises: 936f4e6084f7
Create Date: 2021-04-04 14:48:55.614044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c995e3096be8'
down_revision = '936f4e6084f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('privatemessages', sa.Column('read', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('privatemessages', 'read')
    # ### end Alembic commands ###
