"""empty message

Revision ID: caa63a5114e4
Revises: 4a974a13bafa
Create Date: 2021-02-25 15:48:33.340608

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'caa63a5114e4'
down_revision = '4a974a13bafa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_ibfk_2', 'users', type_='foreignkey')
    op.drop_column('users', 'rentalcompany_creator')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('rentalcompany_creator', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('users_ibfk_2', 'users', 'rentalcompany', ['rentalcompany_creator'], ['id'])
    # ### end Alembic commands ###
