"""empty message

Revision ID: cda7061218a2
Revises: f861dd79086a
Create Date: 2020-12-23 18:57:42.436613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cda7061218a2'
down_revision = 'f861dd79086a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('arena', sa.Column('img', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('arena', 'img')
    # ### end Alembic commands ###
