"""empty message

Revision ID: d0ca37e95def
Revises: 34246ea2315f
Create Date: 2020-12-24 11:08:45.422686

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd0ca37e95def'
down_revision = '34246ea2315f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('arena_city')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('arena_city',
    sa.Column('city_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('arena_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['arena_id'], ['arena.id'], name='arena_city_ibfk_2'),
    sa.ForeignKeyConstraint(['city_id'], ['city.id'], name='arena_city_ibfk_1'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
