"""empty message

Revision ID: d902a5adf20e
Revises: 990b8b6a3452
Create Date: 2020-12-26 02:26:02.395382

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd902a5adf20e'
down_revision = '990b8b6a3452'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('users_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'document', 'users', ['users_id'], ['id'])
    op.drop_constraint('users_ibfk_1', 'users', type_='foreignkey')
    op.drop_column('users', 'document_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('document_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('users_ibfk_1', 'users', 'document', ['document_id'], ['id'])
    op.drop_constraint(None, 'document', type_='foreignkey')
    op.drop_column('document', 'users_id')
    # ### end Alembic commands ###
