"""empty message

Revision ID: da1d0ead96a6
Revises: 92c24253f415
Create Date: 2020-11-20 22:10:01.724244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da1d0ead96a6'
down_revision = '92c24253f415'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('tour_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'event', 'tour', ['tour_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'event', type_='foreignkey')
    op.drop_column('event', 'tour_id')
    # ### end Alembic commands ###
