"""empty message

Revision ID: dd46d5be94b7
Revises: 9df69de3b1f0
Create Date: 2021-03-25 11:25:00.619732

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dd46d5be94b7'
down_revision = '9df69de3b1f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('RolesCompany')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('RolesCompany',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=250), nullable=False),
    sa.Column('title', mysql.VARCHAR(length=250), nullable=True),
    sa.Column('description', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('edit_time', mysql.DATETIME(), nullable=True),
    sa.Column('create_time', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
