"""empty message

Revision ID: def711c4f9b7
Revises: 638e43d43ae8
Create Date: 2021-01-03 10:18:06.068622

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'def711c4f9b7'
down_revision = '638e43d43ae8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('alias', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artist', 'alias')
    # ### end Alembic commands ###
