"""empty message

Revision ID: e077ad0016e7
Revises: 750cf9d1b081
Create Date: 2020-12-22 20:57:11.292630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e077ad0016e7'
down_revision = '750cf9d1b081'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('typehall', sa.Column('create_time', sa.DateTime(), nullable=True))
    op.add_column('typehall', sa.Column('edit_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('typehall', 'edit_time')
    op.drop_column('typehall', 'create_time')
    # ### end Alembic commands ###
