"""empty message

Revision ID: e674ed58e4da
Revises: 3c804bad8c21
Create Date: 2021-02-28 00:44:29.743405

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e674ed58e4da'
down_revision = '3c804bad8c21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('confirmation', sa.Column('conf_id', sa.String(length=128), nullable=True))
    op.drop_column('confirmation', 'cond_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('confirmation', sa.Column('cond_id', mysql.VARCHAR(length=128), nullable=True))
    op.drop_column('confirmation', 'conf_id')
    # ### end Alembic commands ###
