"""empty message

Revision ID: eb5ed182661f
Revises: 22942a4cb10c
Create Date: 2021-01-09 22:03:39.991402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb5ed182661f'
down_revision = '22942a4cb10c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('arena', sa.Column('email', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('arena', 'email')
    # ### end Alembic commands ###
