"""empty message

Revision ID: edced96f012b
Revises: 85330d1b547a
Create Date: 2021-02-25 15:34:10.624420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edced96f012b'
down_revision = '85330d1b547a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rentalcompany', sa.Column('creator_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'rentalcompany', 'users', ['creator_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rentalcompany', type_='foreignkey')
    op.drop_column('rentalcompany', 'creator_id')
    # ### end Alembic commands ###
