"""empty message

Revision ID: f151313620a7
Revises: 0bf089390d9c
Create Date: 2021-03-16 17:48:02.173049

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f151313620a7'
down_revision = '0bf089390d9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('equipment', sa.Column('created', sa.DateTime(), nullable=True))
    op.add_column('equipment', sa.Column('edit', sa.DateTime(), nullable=True))
    op.drop_constraint('equipment_ibfk_1', 'equipment', type_='foreignkey')
    op.drop_column('equipment', 'edit_equipment')
    op.drop_column('equipment', 'created_equipment')
    op.drop_column('equipment', 'category_id')
    op.add_column('equipment_subcategory', sa.Column('description', sa.String(length=256), nullable=True))
    op.add_column('equipmentcategory', sa.Column('created', sa.DateTime(), nullable=True))
    op.add_column('equipmentcategory', sa.Column('description', sa.String(length=256), nullable=True))
    op.add_column('equipmentcategory', sa.Column('edit', sa.DateTime(), nullable=True))
    op.drop_column('equipmentcategory', 'created_equipmentcategory')
    op.drop_column('equipmentcategory', 'edit_equipmentcategory')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('equipmentcategory', sa.Column('edit_equipmentcategory', mysql.DATETIME(), nullable=True))
    op.add_column('equipmentcategory', sa.Column('created_equipmentcategory', mysql.DATETIME(), nullable=True))
    op.drop_column('equipmentcategory', 'edit')
    op.drop_column('equipmentcategory', 'description')
    op.drop_column('equipmentcategory', 'created')
    op.drop_column('equipment_subcategory', 'description')
    op.add_column('equipment', sa.Column('category_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('equipment', sa.Column('created_equipment', mysql.DATETIME(), nullable=True))
    op.add_column('equipment', sa.Column('edit_equipment', mysql.DATETIME(), nullable=True))
    op.create_foreign_key('equipment_ibfk_1', 'equipment', 'equipmentcategory', ['category_id'], ['id'])
    op.drop_column('equipment', 'edit')
    op.drop_column('equipment', 'created')
    # ### end Alembic commands ###
