"""empty message

Revision ID: f861dd79086a
Revises: e077ad0016e7
Create Date: 2020-12-22 21:00:15.765799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f861dd79086a'
down_revision = 'e077ad0016e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('create_time', sa.DateTime(), nullable=True))
    op.add_column('roles', sa.Column('edit_time', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('create_time', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('edit_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'edit_time')
    op.drop_column('users', 'create_time')
    op.drop_column('roles', 'edit_time')
    op.drop_column('roles', 'create_time')
    # ### end Alembic commands ###
