"""empty message

Revision ID: ff1aad233b5a
Revises: 0efa9940e6af
Create Date: 2020-12-20 21:41:47.786654

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ff1aad233b5a'
down_revision = '0efa9940e6af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'login',
               existing_type=mysql.VARCHAR(length=250),
               nullable=True)
    op.alter_column('users', 'name',
               existing_type=mysql.VARCHAR(length=250),
               nullable=True)
    op.create_unique_constraint(None, 'users', ['login'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.alter_column('users', 'name',
               existing_type=mysql.VARCHAR(length=250),
               nullable=False)
    op.alter_column('users', 'login',
               existing_type=mysql.VARCHAR(length=250),
               nullable=False)
    # ### end Alembic commands ###
